# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aix < Formula
  desc "CLI to switch Anthropic-compatible endpoints and tokens"
  homepage "https://github.com/h4ck4life/aix-go"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/h4ck4life/aix-go/releases/download/v1.0.1/aix_1.0.1_darwin_amd64.tar.gz"
      sha256 "663bffc2d98f9a72d1e0fc7f290b369fc529f68f61bc144af768deea4816f53a"

      define_method(:install) do
        bin.install "aix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/h4ck4life/aix-go/releases/download/v1.0.1/aix_1.0.1_darwin_arm64.tar.gz"
      sha256 "cfc812e0d325116bd80721e0e7312596d7acbadb3c97069a165ad8cf64ca2751"

      define_method(:install) do
        bin.install "aix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/h4ck4life/aix-go/releases/download/v1.0.1/aix_1.0.1_linux_amd64.tar.gz"
      sha256 "e191e26bd823e46def51a50f580ded4422f001efec606c539817179bce88bddd"
      define_method(:install) do
        bin.install "aix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/h4ck4life/aix-go/releases/download/v1.0.1/aix_1.0.1_linux_arm64.tar.gz"
      sha256 "aab71bd8f89d5547e6fd582cf4820d8fb700f21c14e35e2413e6e2db7375baab"
      define_method(:install) do
        bin.install "aix"
      end
    end
  end

  test do
    system "#{bin}/aix", "--version"
  end
end
