# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aix < Formula
  desc "CLI to switch Anthropic-compatible endpoints and tokens"
  homepage "https://github.com/h4ck4life/aix-go"
  version "1.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/h4ck4life/aix-go/releases/download/v1.0.6/aix_1.0.6_darwin_amd64.tar.gz"
      sha256 "8d2d3366fdb8976227416e5a8f66ba3d36ca0aa7faa8ded139f8c95839098987"

      define_method(:install) do
        bin.install "aix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/h4ck4life/aix-go/releases/download/v1.0.6/aix_1.0.6_darwin_arm64.tar.gz"
      sha256 "38b4efa8306100637b8a78b5d76cc881e146d0e01ce1ec3d53d2ba600c9c53cc"

      define_method(:install) do
        bin.install "aix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/h4ck4life/aix-go/releases/download/v1.0.6/aix_1.0.6_linux_amd64.tar.gz"
      sha256 "5eef9506f6b75d9a738b61611a13a4676a8633187a236698f5f03e043dea0b3a"
      define_method(:install) do
        bin.install "aix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/h4ck4life/aix-go/releases/download/v1.0.6/aix_1.0.6_linux_arm64.tar.gz"
      sha256 "1ed4e069c8224b91ff3fbb504a8f3579570456734bc19d163cd1606c28a7d4b8"
      define_method(:install) do
        bin.install "aix"
      end
    end
  end

  test do
    system "#{bin}/aix", "--version"
  end
end
